# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "middleman", "~> 3.3.10"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.4.2"

# js engine
gem 'therubyracer'

# sass extensions
gem 'bourbon'
gem 'neat'

# rake
gem 'rake'

# cmi
gem 'curo-material-interface', path: '../'

# debugging
gem 'byebug'
